from router import user_router
from router import admin_router
from router import contact_router
from router import newsletter_router
from router import image_router
from router import product_router
from router import payments_router
from router import events_router
from router import orders_router